name: Run gcp script
on:
  workflow_dispatch:
    inputs:
      projects:
        description: Enter the project name
        required: true
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_LOGGING_SA_KEY }}
          export_default_credentials: true

      - name: Run Shell Script
        run: |
          echo ${{ secrets.GCP_LOGGING_SA_KEY }} > ./centralized-sa.json
          gcloud auth activate-service-account --key-file="./centralized-sa.json"
          rm ./centralized-sa.json
          bash gcp-script.sh