name: Run gcp script
on:
  workflow_dispatch:
    inputs:
      projects:
        description: Enter the project name
        required: true
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_LOGGING_SA_KEY }}
          export_default_credentials: true

      - name: Run Shell Script
        run: ./gcp-script.sh
        shell: bash
        
           